# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: macOS Malware Encyclopedia
email: macOs@gmail.com

#write html inside the double quotes to display in jumbotron
description: "macOS Malware Encyclopedia"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
twitter_username: megabeets_
github_username:  itayc0hen

# Build settings
markdown: kramdown


collections:
  families:
    output: true
    permalink: /:collection/:path/
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"